version: "3.7"

services:

  rtsp-publisher:
    restart: unless-stopped
    image: jrottenberg/ffmpeg
    entrypoint: /bin/sh
    command:
      - '-c'
      - ffmpeg -re -stream_loop -1 -i /media/${MP4_FILE:-badminton.mp4} -f rtsp -rtsp_transport tcp rtsp://rtsp:8554/${MP4_FILE:-badminton.mp4}
    volumes:
      - ./rtsp-streamer-server/media:/media

  rtsp:
    restart: unless-stopped
    image: aler9/rtsp-simple-server
    ports:
      - ${RTSP_PORT:-554}:8554

  # sample
  # Player URL - http://<server>:8888/test/h264w.html
  # URL for player to play: rtsp://rtsp:8554/badminton.mp4
  wsrtsp:
    restart: unless-stopped
    image: farmer1992/nginx-websockify
    ports:
      - ${WS_RTSP_PORT:-8888}:80
    volumes:
      - ./rtsp-ws-server/conf.d:/etc/nginx/conf.d
      - ./rtsp-ws-server/html:/usr/share/nginx/html
